chrome:
  launcher:
    port: 9222
    chromeFlags:
      - --headless
      - --disable-gpu
      - --no-sandbox
  device:
    deviceScaleFactor: 0
    mobile: true
    fitWindow: false
# chrome developer toolsから取得
device:
  iphone6:
    userAgent: "Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1"
    width: 375
    height: 667
  desktop:
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
    width: 1980
    height: 1080
